### ISSUE TITLE
[Bug] Homepage FAQ overlapping

### ISSUE THREAD

**Issue by limjunyong** [NUS-Fintech-Society/SD_Fintech_Month_2023#70]
![photo_2022-12-07_23-28-39](https://user-images.githubusercontent.com/61913613/206220673-445845f0-fb91-425e-8d8f-e27005be8a68.jpg)

-> for mobile view

**Comment by nicleejy** [comment]
Implemented a fix in latest PR

**Comment by Jiwei99** [comment]
Done
