### ISSUE TITLE
[FE Improvement] Writeup for Theme

### ISSUE THREAD

**Issue by limjunyong** [NUS-Fintech-Society/SD_Fintech_Month_2023#71]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/61913613/206227016-c3d94b99-7d39-46fe-9767-9e2263229f4f.png">

https://www.figma.com/file/WUOaljKO7ORqTZ0bDnJHzO/NUS-Fintech-Month-Milestone-1?node-id=174%3A124&t=x9szTMEkIJYu46Zn-4

Fintech as a Service
"The theme for NUS Fintech Month 2023 will be "Fintech As A Service" and for the purpose of the hackathon, we define Fintech as a Service (FaaS) as allowing any organization to use APIs to embed useful financial-related capabilities into their existing applications, products, and services."

**Comment by nicleejy** [comment]
Added in latest PR

**Comment by Jiwei99** [comment]
Done
